services:
  
 frontend:
    build:
      context: ./client
    container_name: InvoiceHub-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - InvoiceHub-app
    restart: unless-stopped



 backend:
    build:
      context: ./server
    container_name: InvoiceHub-backend
    ports:
      - "5219:5219"
    
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - EMAIL_USER= ${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - mongodb
    networks:
      - InvoiceHub-app
    restart: unless-stopped
 





 mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"

    volumes:
      - InvoiceHub-data:/data/db 
    networks:
      - InvoiceHub-app
   
    restart: unless-stopped


networks:
  InvoiceHub-app:

volumes:
 InvoiceHub-data:



    