apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoicehub-backend-deploy
  namespace: invoicehub-ns

spec:
  replicas: 1

  selector:
    matchLabels:
      app: invoicehub-backend

  template:
    metadata:
      labels:
        app: invoicehub-backend

    spec:
      containers:
        - name: invoicehub-backend-app
          image: somesh9021/invoicehub-backend:v1.0.0
          imagePullPolicy: Always

          ports:
            - containerPort: 5219

          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: NODE_ENV

            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: MONGO_URI

            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: JWT_EXPIRES_IN

            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: CLIENT_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET

            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: EMAIL_USER

            
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: EMAIL_PASS