apiVersion: apps/v1
kind: Deployment
metadata:
  name: InvoiceHub-backend-deploy
  namespace: invoicehub-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: InvoiceHub-backend
  template:
    metadata:
      name: InvoiceHub-backend-pod 
      labels:
        app: InvoiceHub-backend
    spec:
      containers:
      - name: InvoiceHub-backend-app
        image: somesh9021/invoicehub-backend:v1.0.0
        ports:
        - containerPort: 5219
        imagePullPolicy: Always

        env:
         - name: NODE_ENV
         - valueFrom:
             configMapKeyref:
                name: backend-configmap
                key: NODE_ENV



         - name: MONGO_URI
         - valueFrom:
             configMapKeyref:
                name: backend-configmap
                key: MONGO_URI



         - name: JWT_SECRET
         - valueFrom:
             secretKeyref:
                name: backend-secrets
                key: JWT_SECRET

         - name: JWT_EXPIRES_IN
         - valueFrom:
             configMapKeyref:
                name: backend-configmap
                key: JWT_EXPIRES_IN


          
         - name: CLIENT_URL
         - valueFrom:
             configMapKeyref:
                name: backend-configmap
                key: CLIENT_URL
              