apiVersion: apps/v1
kind: Deployment
metadata:
  name: InvoiceHub-backend-deploy
  namespace: InvoiceHub-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: InvoiceHub-backend
  template:
    metadata:
      name: InvoiceHub-backend-pod 
      labels:
        app: InvoiceHub-backend
    spec:
      containers:
      - name: InvoiceHub-backend-app
        image: somesh9021/invoicehub-backend:v1.0.0
        ports:
        - containerPort: 5219
        imagePullPolicy: Always

        env:
         - name: NODE_ENV
         - value: 

