kind: ConfigMap
apiVersion: v1 

metadata: 
  name: backend-configmap
  namespace: invoicehub-ns
data:
  NODE_ENV : "production"
  MONGO_URI : "mongodb://mongodb:27017/InvoiceHub"
  JWT_EXPIRES_IN: "7d"
  CLIENT_URL: "http://65.0.183.210:3000"