apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoicehub-frontend-deploy
  namespace: invoicehub-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoicehub-frontend
  template:
    metadata:
      name: invoicehub-front-pod 
      labels:
        app: invoicehub-frontend
    spec:
      containers:
      - name: invoicehub-frontend-app
        image: somesh9021/invoicehub-frontend:v1.0.0
        ports:
        - containerPort: 80
        env:
          - name: REACT_APP_API_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-configmap
                key: REACT_APP_API_URL