apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: invoicehub-ns
spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /mnt/data/mongo